# Generated by Django 4.2 on 2024-03-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuespedReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huesped reserva',
                'verbose_name_plural': 'Huespedes reservas',
                'db_table': 'huespedReserva',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('cancelar', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=4)),
                ('importe_estadia', models.FloatField()),
                ('importe_otros_gasto', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
                ('descuento_importe_noche', models.IntegerField(choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=1)),
                ('descuento_total_calcularo', models.IntegerField(choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=1)),
                ('aumento_total', models.IntegerField(choices=[(0, '0'), (4, '4'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50')], default=1)),
                ('porcentaje_de_senia', models.IntegerField(choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=1)),
                ('total_senia', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.huespedreserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['id'],
            },
        ),
    ]
