# Generated by Django 4.2 on 2024-03-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('demas_huespedes', models.CharField(blank=True, max_length=1500, null=True)),
                ('patente_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=40, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('penalidad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
                'db_table': 'huesped',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('importe_estadia', models.FloatField()),
                ('importe_otros_gasto', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0)),
                ('estado', models.BooleanField()),
                ('descuento_importe_noche', models.IntegerField(choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=1)),
                ('descuento_total_calcularo', models.IntegerField(choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (70, '70')], default=1)),
                ('aumento_total', models.IntegerField(choices=[(0, '0'), (4, '4'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50')], default=1)),
                ('total_consumidos', models.FloatField(default=0.0)),
                ('porcentaje_de_senia_reservas', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('habitacion_reserva', models.CharField(blank=True, max_length=40, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.huesped')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
    ]
