# Generated by Django 4.2 on 2024-03-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_numero', models.CharField(max_length=40)),
                ('piso', models.CharField(choices=[('planta baja', 'planta baja'), ('primero', 'primero'), ('segundo', 'segundo'), ('tercero', 'tercero'), ('cuarto', 'cuarto'), ('quinto', 'quinto'), ('sexto', 'sexto'), ('séptimo', 'séptimo'), ('octavo', 'octavo'), ('noveno', 'noveno'), ('décimo', 'décimo'), ('décimo primero', 'décimo primero'), ('décimo segundo', 'décimo segundo')], default=1, max_length=18)),
                ('capacidad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('precio_por_noche', models.FloatField()),
                ('camita_bebe', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_heladera', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_aire_acondicionado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_calefaccion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_ventana', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_cama_matrimonial', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_televisor', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_wifi', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('jacuzzi', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('posee_microondas', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=4)),
                ('check_out_lates', models.FloatField()),
                ('otro_dato', models.CharField(blank=True, max_length=50, null=True)),
                ('libre', models.CharField(default='LIBRE', max_length=10)),
                ('ocupada', models.CharField(default='OCUPADA', max_length=10)),
                ('post_ocupada', models.CharField(default='POST OCUPADA', max_length=15)),
                ('estado', models.CharField(default='Null', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitaciones',
                'ordering': ['id'],
            },
        ),
    ]
